name: Deploy Client to Firebase Hosting
"on":
  push:
    paths:
      - client/**
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./client
        run: yarn install

      - name: Build
        working-directory: ./client
        run: REACT_APP_BASE_URL=${{ secrets.REACT_APP_BASE_URL }} yarn build
        env:
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}

      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting:client --project=trackcta-website --token=${{ secrets.CLIENT_FIREBASE_TOKEN }} --non-interactive
