name: Build Locales

'on':
  push:
   paths:
    - server/res/en.json
   branches:
    - main
jobs:
  build-locales:
    runs-on: ubuntu-latest
  steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run node script
        working-directory: ./locales
        run: node app.js