name: Deploy Web App to Firebase Hosting
"on":
  push:
    paths:
      - web-app/**
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ./web-app
        run: yarn install

      - name: Build
        working-directory: ./web-app
        run: yarn build
        env:
          REACT_APP_MAPS_API_KEY: ${{ secrets.REACT_APP_MAPS_API_KEY }}
          REACT_APP_BASE_URL: ${{ secrets.REACT_APP_BASE_URL }}

      - name: Deploy to Firebase Hosting
        run: |
          npm install -g firebase-tools
          firebase deploy --only hosting:app --project=trackcta --token=${{ secrets.FIREBASE_HOSTING_TOKEN }} --non-interactive
